In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

# Create Data Frame

In [4]:
data = {
    "name" : ["udith","ahinram","divya"],
    "age" : [21,40,60],
    "Salary" : [250000,10000,5000]
}

df = pd.DataFrame(data)

### FROM LIST

# READ FILES

In [2]:
df = pd.read_excel("C:/Users/Administrator/Downloads/TCS_5_Years_Stock_Data.xlsx")

pd.read_csv("data.csv")
pd.read_excel("data.xlsx")
pd.read_json("data.json")
pd.read_sql(query, connection)

# Save Files

In [21]:
df.to_csv("udith.csv",index=False)

In [12]:
df.to_excel("pandas.xlsx",index=False)

In [23]:
df.to_json("pandas.json")

# view Files

## First 5 rows

In [45]:
df.head(5)

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334

## Last 5 rows

In [48]:
df.tail(5)

,Price,Close,High,Low,Open,Volume
1235,2026-07-13 00:00:00,2169.604248,2192.87655,2053.839076,2063.684994,12382622
1236,2026-07-14 00:00:00,2188.600098,2215.850587,2167.117787,2170.996423,9546290
1237,2026-07-15 00:00:00,2189.199951,2202.899902,2145.399902,2174.100098,5426489
1238,2026-07-16 00:00:00,2201,2231.399902,2187.800049,2206,5197595
1239,2026-07-17 00:00:00,NaN,NaN,NaN,NaN,5614004

## Random rows

In [49]:
df.sample(5)

,Price,Close,High,Low,Open,Volume
931,2025-04-24 00:00:00,3226.29541,3236.633576,3213.111621,3225.821178,2252175
127,2022-01-18 00:00:00,3473.280273,3517.755818,3464.054315,3511.010486,2389041
889,2025-02-17 00:00:00,3703.27832,3731.258013,3657.467455,3657.752041,1799806
649,2024-02-28 00:00:00,3790.337891,3823.419509,3762.77714,3768.850678,1939225
1176,2026-04-21 00:00:00,2561.532959,2564.967307,2511.980224,2511.980224,2719959

## Rows and Columns

In [50]:
df.shape

(1240, 6)

## Columns

In [54]:
df.columns

Index(['Price', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

## INDEX

In [56]:
df.index

RangeIndex(start=0, stop=1240, step=1)

## DATA SET INFORMATION

In [58]:
df.info

<bound method DataFrame.info of                     Price        Close         High          Low         Open  \
0                  Ticker       TCS.NS       TCS.NS       TCS.NS       TCS.NS
1                    Date          NaN          NaN          NaN          NaN
2     2021-07-19 00:00:00  2766.457764  2779.661941  2758.986871  2762.461665
3     2021-07-20 00:00:00  2784.873779  2792.865763   2741.74277  2766.457413
4     2021-07-22 00:00:00  2794.038574  2801.509254  2771.148283  2771.148283
...                   ...          ...          ...          ...          ...
1235  2026-07-13 00:00:00  2169.604248   2192.87655  2053.839076  2063.684994
1236  2026-07-14 00:00:00  2188.600098  2215.850587  2167.117787  2170.996423
1237  2026-07-15 00:00:00  2189.199951  2202.899902  2145.399902  2174.100098
1238  2026-07-16 00:00:00         2201  2231.399902  2187.800049         2206
1239  2026-07-17 00:00:00          NaN          NaN          NaN          NaN

        Volume
0       TCS.NS
1          NaN
2      1597058
3      1811945
4      2859334
...        ...
1235  12382622
1236   9546290
1237   5426489
1238   5197595
1239   5614004

[1240 rows x 6 columns]>

## statistical summary

In [59]:
df.describe()

         Price        Close    High     Low    Open  Volume
count     1240  1238.000000    1238    1238    1238    1239
unique    1240  1226.000000    1238    1238    1238    1235
top     Ticker  3317.443115  TCS.NS  TCS.NS  TCS.NS       0
freq         1     3.000000       1       1       1       5

# SELECT DATA

## Single Columns

In [60]:
df["Price"]

0                    Ticker
1                      Date
2       2021-07-19 00:00:00
3       2021-07-20 00:00:00
4       2021-07-22 00:00:00
               ...
1235    2026-07-13 00:00:00
1236    2026-07-14 00:00:00
1237    2026-07-15 00:00:00
1238    2026-07-16 00:00:00
1239    2026-07-17 00:00:00
Name: Price, Length: 1240, dtype: object

## Multiple columns

In [62]:
df[["High","Low"]]

             High          Low
0          TCS.NS       TCS.NS
1             NaN          NaN
2     2779.661941  2758.986871
3     2792.865763   2741.74277
4     2801.509254  2771.148283
...           ...          ...
1235   2192.87655  2053.839076
1236  2215.850587  2167.117787
1237  2202.899902  2145.399902
1238  2231.399902  2187.800049
1239          NaN          NaN

[1240 rows x 2 columns]

## Row By Position

In [67]:
df.iloc[0]
df.iloc[0:10]

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334
5,2021-07-23 00:00:00,2790.998047,2815.929651,2785.611947,2805.896141,1776193
6,2021-07-26 00:00:00,2777.707031,2800.90124,2771.886794,2779.8353,1259611
7,2021-07-27 00:00:00,2765.023682,2788.522017,2746.086013,2779.835033,1121367
8,2021-07-28 00:00:00,2777.924805,2783.701566,2721.111781,2769.411515,1660654
9,2021-07-29 00:00:00,2776.187012,2801.94384,2771.409169,2780.052678,1731997

# Row By Label

In [69]:
df.loc[0]
df.loc[0:3]

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945

## Filtering

In [87]:
df["High"].dtype

dtype('O')

In [90]:
df["High"] = pd.to_numeric(df["High"], errors="coerce").astype(float)

In [92]:
df[df["High"] > 3000]

,Price,Close,High,Low,Open,Volume,P,H
20,NaN,3008.649902,3023.070380,2916.654828,2919.478098,4363584,3023.070380,3023.070380
21,NaN,3016.947021,3035.537300,2985.282997,3005.697416,2083489,3035.537300,3035.537300
22,NaN,3086.529541,3093.261955,3008.303191,3024.895419,4336019,3093.261955,3093.261955
23,NaN,3093.044678,3122.971300,3072.23939,3104.598411,2631309,3122.971300,3122.971300
24,NaN,3092.132568,3105.597396,3040.445003,3045.657195,2836148,3105.597396,3105.597396
...,...,...,...,...,...,...,...,...
1123,NaN,3085.417969,3140.073353,3066.970806,3140.073353,2457641,3140.073353,3140.073353
1124,NaN,3065.30249,3082.081828,3034.000959,3082.081828,3022068,3082.081828,3082.081828
1125,NaN,3110.145508,3138.012692,3075.213188,3138.012692,2636272,3138.012692,3138.012692
1126,NaN,3164.800537,3287.161392,3126.532091,3287.161392,4366060,3287.161392,3287.161392
1127,NaN,2942.84375,3061.475843,2929.989381,3061.475843,10852595,3061.475843,3061.475843

In [7]:
df["Open"] = pd.to_numeric(df["Open"], errors="coerce").astype(float)
df["Close"] = pd.to_numeric(df["Close"], errors="coerce").astype(float)

In [8]:
df[(df["Open"] > 2000) & (df["Close"] > 2000)]

,Price,Close,High,Low,Open,Volume
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334
5,2021-07-23 00:00:00,2790.998047,2815.929651,2785.611947,2805.896141,1776193
6,2021-07-26 00:00:00,2777.707031,2800.90124,2771.886794,2779.835300,1259611
...,...,...,...,...,...,...
1234,2026-07-10 00:00:00,2057.717529,2121.666943,2053.34162,2093.720078,6714551
1235,2026-07-13 00:00:00,2169.604248,2192.87655,2053.839076,2063.684994,12382622
1236,2026-07-14 00:00:00,2188.600098,2215.850587,2167.117787,2170.996423,9546290
1237,2026-07-15 00:00:00,2189.199951,2202.899902,2145.399902,2174.100098,5426489
1238,2026-07-16 00:00:00,2201.000000,2231.399902,2187.800049,2206.000000,5197595

# Sorting

In [18]:
df.sort_values("High")

df.sort_values("High", ascending=True)

df.sort_values(["Open","Close"])

,Price,Close,High,Low,Open,Volume
1228,2026-07-02 00:00:00,2056.822754,2065.574573,1991.580373,1997.050382,6040621
1227,2026-07-01 00:00:00,1971.788818,2040.810403,1966.020519,2028.776409,4658295
1231,2026-07-07 00:00:00,2084.669922,2111.124725,2037.826664,2038.821211,4769048
1233,2026-07-09 00:00:00,2038.323975,2053.739452,2005.006652,2046.280350,3791498
1222,2026-06-24 00:00:00,2097.499512,2109.135662,2049.761258,2049.761258,4747277
...,...,...,...,...,...,...
765,2024-08-22 00:00:00,4182.630859,4237.399164,4178.17155,4236.516375,1829872
772,2024-09-02 00:00:00,4200.329102,4262.529888,4191.921285,4251.381161,1216500
0,Ticker,NaN,NaN,TCS.NS,NaN,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
1239,2026-07-17 00:00:00,NaN,NaN,NaN,NaN,5614004

# MISSING VALUES

In [5]:
df.isnull()

      Price  Close   High    Low   Open  Volume
0     False  False  False  False  False   False
1     False   True   True   True   True    True
2     False  False  False  False  False   False
3     False  False  False  False  False   False
4     False  False  False  False  False   False
...     ...    ...    ...    ...    ...     ...
1235  False  False  False  False  False   False
1236  False  False  False  False  False   False
1237  False  False  False  False  False   False
1238  False  False  False  False  False   False
1239  False   True   True   True   True   False

[1240 rows x 6 columns]

In [6]:
df.isnull().sum()

Price     0
Close     2
High      2
Low       2
Open      2
Volume    1
dtype: int64

In [7]:
df.dropna

<bound method DataFrame.dropna of                     Price        Close         High          Low         Open  \
0                  Ticker       TCS.NS       TCS.NS       TCS.NS       TCS.NS
1                    Date          NaN          NaN          NaN          NaN
2     2021-07-19 00:00:00  2766.457764  2779.661941  2758.986871  2762.461665
3     2021-07-20 00:00:00  2784.873779  2792.865763   2741.74277  2766.457413
4     2021-07-22 00:00:00  2794.038574  2801.509254  2771.148283  2771.148283
...                   ...          ...          ...          ...          ...
1235  2026-07-13 00:00:00  2169.604248   2192.87655  2053.839076  2063.684994
1236  2026-07-14 00:00:00  2188.600098  2215.850587  2167.117787  2170.996423
1237  2026-07-15 00:00:00  2189.199951  2202.899902  2145.399902  2174.100098
1238  2026-07-16 00:00:00         2201  2231.399902  2187.800049         2206
1239  2026-07-17 00:00:00          NaN          NaN          NaN          NaN

        Volume
0       TCS.NS
1          NaN
2      1597058
3      1811945
4      2859334
...        ...
1235  12382622
1236   9546290
1237   5426489
1238   5197595
1239   5614004

[1240 rows x 6 columns]>

In [8]:
df.fillna(0)

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,0,0,0,0,0
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334
...,...,...,...,...,...,...
1235,2026-07-13 00:00:00,2169.604248,2192.87655,2053.839076,2063.684994,12382622
1236,2026-07-14 00:00:00,2188.600098,2215.850587,2167.117787,2170.996423,9546290
1237,2026-07-15 00:00:00,2189.199951,2202.899902,2145.399902,2174.100098,5426489
1238,2026-07-16 00:00:00,2201,2231.399902,2187.800049,2206,5197595
1239,2026-07-17 00:00:00,0,0,0,0,5614004

In [9]:
df.fillna(df.mean(numeric_only=True))

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334
...,...,...,...,...,...,...
1235,2026-07-13 00:00:00,2169.604248,2192.87655,2053.839076,2063.684994,12382622
1236,2026-07-14 00:00:00,2188.600098,2215.850587,2167.117787,2170.996423,9546290
1237,2026-07-15 00:00:00,2189.199951,2202.899902,2145.399902,2174.100098,5426489
1238,2026-07-16 00:00:00,2201,2231.399902,2187.800049,2206,5197595
1239,2026-07-17 00:00:00,NaN,NaN,NaN,NaN,5614004

# Duplicates

In [11]:
df.duplicated()
df.drop_duplicates()

,Price,Close,High,Low,Open,Volume
0,Ticker,TCS.NS,TCS.NS,TCS.NS,TCS.NS,TCS.NS
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-07-19 00:00:00,2766.457764,2779.661941,2758.986871,2762.461665,1597058
3,2021-07-20 00:00:00,2784.873779,2792.865763,2741.74277,2766.457413,1811945
4,2021-07-22 00:00:00,2794.038574,2801.509254,2771.148283,2771.148283,2859334
...,...,...,...,...,...,...
1235,2026-07-13 00:00:00,2169.604248,2192.87655,2053.839076,2063.684994,12382622
1236,2026-07-14 00:00:00,2188.600098,2215.850587,2167.117787,2170.996423,9546290
1237,2026-07-15 00:00:00,2189.199951,2202.899902,2145.399902,2174.100098,5426489
1238,2026-07-16 00:00:00,2201,2231.399902,2187.800049,2206,5197595
1239,2026-07-17 00:00:00,NaN,NaN,NaN,NaN,5614004

# UNIQUE

In [3]:
df["Open"].unique()

array(['TCS.NS', nan, 2762.461665108622, ..., 2170.996422535663,
       2174.10009765625, 2206], shape=(1239,), dtype=object)

In [4]:
df["Open"].nunique()

1238

In [5]:
df["Open"].value_counts()

Open
TCS.NS         1
3851.037834    1
4059.608641    1
4024.310732    1
3986.079618    1
              ..
3007.762627    1
2989.623648    1
3054.688202    1
3035.737264    1
2206           1
Name: count, Length: 1238, dtype: int64

# Basic Statistics

In [7]:
df["High"] = pd.to_numeric(df["High"], errors="coerce")

In [8]:
df["High"].sum()

np.float64(3956531.9021826256)

In [9]:
df["High"].max()

4266.47830377286

In [10]:
df["High"].min()

2040.810403055538

In [11]:
df["High"].mean()

np.float64(3198.48981583074)

In [13]:
df["High"].median()

3134.236349199543

In [14]:
df["High"].std() #standard deviation

445.41311585967003

In [15]:
df["High"].count()

np.int64(1237)

# Change Data types

In [20]:
print(df.dtypes)

Price      object
Close      object
High      float64
Low        object
Open       object
Volume     object
dtype: object

In [36]:
## Automatically convert numeric values 
df["Low"] = pd.to_numeric(df["Low"], errors="coerce")
df["Price"] = pd.to_numeric(df["Price"],errors="coerce")
df["Close"] = pd.to_numeric(df["Close"],errors="coerce")
df["Open"] = pd.to_numeric(df["Open"],errors="coerce")
df["Volume"] = pd.to_numeric(df["Volume"],errors="coerce")

In [37]:
print(df.dtypes)

Price     float64
Close     float64
High      float64
Low       float64
Open      float64
Volume    float64
dtype: object

In [38]:
df.head(10)

   Price        Close         High          Low         Open     Volume
0    NaN          NaN          NaN          NaN          NaN        NaN
1    NaN          NaN          NaN          NaN          NaN        NaN
2    NaN  2766.457764  2779.661941  2758.986871  2762.461665  1597058.0
3    NaN  2784.873779  2792.865763  2741.742770  2766.457413  1811945.0
4    NaN  2794.038574  2801.509254  2771.148283  2771.148283  2859334.0
5    NaN  2790.998047  2815.929651  2785.611947  2805.896141  1776193.0
6    NaN  2777.707031  2800.901240  2771.886794  2779.835300  1259611.0
7    NaN  2765.023682  2788.522017  2746.086013  2779.835033  1121367.0
8    NaN  2777.924805  2783.701566  2721.111781  2769.411515  1660654.0
9    NaN  2776.187012  2801.943840  2771.409169  2780.052678  1731997.0

# Random Sampling

In [39]:
df.sample(10)

      Price        Close         High          Low         Open     Volume
379     NaN  3081.670654  3085.370660  3028.157382  3057.395671  1067916.0
44      NaN  3321.468506  3362.731682  3307.873460  3308.872378  2002008.0
1142    NaN  2579.980225  2604.413060  2546.323568  2547.304811  3621285.0
426     NaN  2887.740723  2910.256032  2864.052225  2910.256032  1521830.0
594     NaN  3314.270508  3330.994062  3291.744121  3320.027826  1641155.0
978     NaN  3281.860596  3334.776901  3266.358954  3306.070070  2375183.0
698     NaN  3570.819336  3613.655595  3566.310351  3592.996714  1115021.0
555     NaN  3290.403320  3326.954332  3285.937087  3326.954332  2426417.0
844     NaN  4111.995605  4167.688784  4095.045270  4152.787551  1646224.0
1066    NaN  2883.266113  2895.023485  2853.101541  2892.132317  1830520.0

In [40]:
df.sample(frac = 0.2)

      Price        Close         High          Low         Open     Volume
730     NaN  3723.759277  3729.320724  3691.456677  3701.699053  2307449.0
1086    NaN  3120.727051  3152.915533  3105.500184  3112.824571  5244013.0
1205    NaN  2284.872070  2322.267133  2267.567050  2271.545238  7505095.0
1182    NaN  2428.280029  2441.232378  2401.688509  2405.024637  2835961.0
62      NaN  3143.280518  3194.240445  3140.451831  3155.074009  6442299.0
...     ...          ...          ...          ...          ...        ...
943     NaN  3333.851562  3436.285693  3329.583474  3433.819594  3062887.0
524     NaN  3082.036133  3086.137858  3053.734187  3076.293673  1158046.0
886     NaN  3746.575439  3814.485563  3737.090798  3766.445948  1678002.0
979     NaN  3275.736572  3339.465598  3272.578774  3336.882030  3090585.0
284     NaN  2771.915039  2782.739910  2730.022919  2730.022919  1291534.0

[248 rows x 6 columns]

# Correlation

In [41]:
df.corr(numeric_only=True)

        Price     Close      High       Low      Open    Volume
Price     NaN       NaN       NaN       NaN       NaN       NaN
Close     NaN  1.000000  0.998620  0.998499  0.996206 -0.233174
High      NaN  0.998620  1.000000  0.998302  0.998265 -0.215252
Low       NaN  0.998499  0.998302  1.000000  0.998403 -0.246878
Open      NaN  0.996206  0.998265  0.998403  1.000000 -0.231602
Volume    NaN -0.233174 -0.215252 -0.246878 -0.231602  1.000000

# Memory usage

In [46]:
df.memory_usage(deep=True)

Index      132
Price     9920
Close     9920
High      9920
Low       9920
Open      9920
Volume    9920
dtype: int64

In [47]:
df.memory_usage(deep=True).sum() #To get the total memory used by the DataFrame:

np.int64(59652)

# The most important NumPy commands for Data Analysts and Data Scientists.

| Command                      | Purpose                                                                                          |
| ---------------------------- | ------------------------------------------------------------------------------------------------ |
| `df.head()`                  | Display the first 5 rows of the DataFrame.                                                       |
| `df.tail()`                  | Display the last 5 rows of the DataFrame.                                                        |
| `df.shape`                   | Return the number of rows and columns as `(rows, columns)`.                                      |
| `df.info()`                  | Show dataset information, including column names, data types, non-null counts, and memory usage. |
| `df.describe()`              | Generate summary statistics for numeric columns.                                                 |
| `df.columns`                 | Display all column names.                                                                        |
| `df.dtypes`                  | Show the data type of each column.                                                               |
| `df.index`                   | Display the row index labels.                                                                    |
| `df.isnull()`                | Check for missing (`NaN`) values.                                                                |
| `df.isnull().sum()`          | Count missing values in each column.                                                             |
| `df.notnull()`               | Check for non-missing values.                                                                    |
| `df.duplicated()`            | Identify duplicate rows.                                                                         |
| `df.duplicated().sum()`      | Count the number of duplicate rows.                                                              |
| `df.dropna()`                | Remove rows containing missing values.                                                           |
| `df.fillna(value)`           | Replace missing values with a specified value.                                                   |
| `df.drop_duplicates()`       | Remove duplicate rows.                                                                           |
| `df.sort_values()`           | Sort rows by one or more columns.                                                                |
| `df.sort_index()`            | Sort the DataFrame by index.                                                                     |
| `df["Column"]`               | Select a single column.                                                                          |
| `df[["Col1", "Col2"]]`       | Select multiple columns.                                                                         |
| `df.loc[]`                   | Select rows and columns by labels.                                                               |
| `df.iloc[]`                  | Select rows and columns by integer positions.                                                    |
| `df.query()`                 | Filter rows using a query expression.                                                            |
| `df.sample()`                | Return random rows from the DataFrame.                                                           |
| `df.groupby()`               | Group data for aggregation and analysis.                                                         |
| `df.agg()`                   | Apply one or more aggregate functions.                                                           |
| `df.merge()`                 | Join two DataFrames based on common columns.                                                     |
| `pd.concat()`                | Combine multiple DataFrames vertically or horizontally.                                          |
| `df.join()`                  | Join DataFrames using their indexes.                                                             |
| `df.value_counts()`          | Count the frequency of unique values.                                                            |
| `df.nunique()`               | Count the number of unique values.                                                               |
| `df.unique()`                | Return unique values from a column.                                                              |
| `df.sum()`                   | Calculate the sum of values.                                                                     |
| `df.mean()`                  | Calculate the average value.                                                                     |
| `df.median()`                | Calculate the median value.                                                                      |
| `df.min()`                   | Return the minimum value.                                                                        |
| `df.max()`                   | Return the maximum value.                                                                        |
| `df.std()`                   | Calculate the standard deviation.                                                                |
| `df.count()`                 | Count non-missing values.                                                                        |
| `df.apply()`                 | Apply a function to rows or columns.                                                             |
| `df.astype()`                | Convert a column to a different data type.                                                       |
| `pd.to_numeric()`            | Convert values to numeric type.                                                                  |
| `pd.to_datetime()`           | Convert values to date/time format.                                                              |
| `df.rename()`                | Rename columns or index labels.                                                                  |
| `df.drop()`                  | Remove rows or columns.                                                                          |
| `df.set_index()`             | Set a column as the index.                                                                       |
| `df.reset_index()`           | Reset the index to the default integer index.                                                    |
| `df.memory_usage()`          | Show memory usage of each column.                                                                |
| `df.memory_usage(deep=True)` | Show accurate memory usage, including string objects.                                            |
| `df.corr()`                  | Calculate the correlation between numeric columns.                                               |
| `df.to_csv()`                | Save the DataFrame to a CSV file.                                                                |
| `df.to_excel()`              | Save the DataFrame to an Excel file.                                                             |
| `pd.read_csv()`              | Read data from a CSV file.                                                                       |
| `pd.read_excel()`            | Read data from an Excel file.                                                                    |